"""add user ownership to persons

Revision ID: 4195bac57f0e
Revises: 4000052c7476
Create Date: 2026-09-01 11:07:15.026744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4195bac57f0e'
down_revision: Union[str, Sequence[str], None] = '4000052c7476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'persons', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persons', type_='foreignkey')
    op.drop_column('persons', 'user_id')
    # ### end Alembic commands ###
