"""create medicines table

Revision ID: 62934a1fb1fb
Revises: 1e9d412e23e7
Create Date: 2026-08-23 20:33:13.503429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62934a1fb1fb'
down_revision: Union[str, Sequence[str], None] = '1e9d412e23e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strength', sa.String(length=50), nullable=False),
    sa.Column('dosage_form', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('quantity_remaining', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicines')
    # ### end Alembic commands ###
