"""add reminder timestamps

Revision ID: dab33b9539ce
Revises: fa2b78a28d93
Create Date: 2026-09-08 17:34:30.541724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab33b9539ce'
down_revision: Union[str, Sequence[str], None] = 'fa2b78a28d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dose_occurrences', sa.Column('first_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('dose_occurrences', sa.Column('second_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dose_occurrences', 'second_reminder_sent_at')
    op.drop_column('dose_occurrences', 'first_reminder_sent_at')
    # ### end Alembic commands ###
